/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SyLibHome {
    }
}
declare global {
    interface HTMLSyLibHomeElement extends Components.SyLibHome, HTMLStencilElement {
    }
    var HTMLSyLibHomeElement: {
        prototype: HTMLSyLibHomeElement;
        new (): HTMLSyLibHomeElement;
    };
    interface HTMLElementTagNameMap {
        "sy-lib-home": HTMLSyLibHomeElement;
    }
}
declare namespace LocalJSX {
    interface SyLibHome {
    }
    interface IntrinsicElements {
        "sy-lib-home": SyLibHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sy-lib-home": LocalJSX.IntrinsicElements["sy-lib-home"] & JSXBase.HTMLAttributes<HTMLSyLibHomeElement>;
        }
    }
}
